### ISSUE TITLE
thumbs up error

### ISSUE THREAD

**Issue by EGL** [yourcelf/dotstorm#10]
The first time I like something after refreshing the page, I get an error. After the first time, it works fine.

**Comment by yourcelf** [comment]
Yup; it's totally busted right now.  It also fails to store the vote on the server.  I'm working on the user model right now and will either have that fixed and usable soon -- if I dont get to it before the conf., will remove the UI.

**Comment by yourcelf** [comment]
Should be working now.  Switched to an up/down tally model rather than a modal vote model; punting on user authentication for now.

fixed in: f3df6a8094870b7a701597688c7427ac705bfbd4
